version: '3'

services:
# first service is the mongo image
  mongo:
    image: mongo:5.0.8
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_ADMINUSERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_ADMINPASSWORD}
      MONGO_INITDB_DATABASE: ${MONGODB_DATABASE}
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

# second service is the mongo express gui
  mongo-express:
    image: mongo-express
    restart:  unless-stopped
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGODB_ADMINUSERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGODB_ADMINPASSWORD}
      ME_CONFIG_MONGODB_SERVER : mongo
      ME_CONFIG_MONGODB_PORT: 27017
    depends_on: 
      - mongo


# declare local mongo driver
volumes:
  mongo_data:
